### ISSUE TITLE
DB schemas

### ISSUE THREAD

**Issue by ooong** [LERN-grace-shopper/grace-shopper#3]
**User**
- Users must have a valid email address
- Users email must be unique
- User is or is not an admin

**Product**
- Must have title, description, price, and inventory quantity
- Must belong to at least one category
- If there is no photo, there must be a placeholder photo used

**Order**
- Orders must belong to a user OR guest session (authenticated vs unauthenticated)
- Orders must contain line items that capture the price, current product ID and quantity
- If a user completes an order, that order should keep the price of the item at the time when they -
 checked out even if the price of the product later changes

**Review**
- All reviews must belong to a product
- All reviews must belong to a user
- All reviews must be at least X characters

**Comment by Asterids** [comment]
Do we need to create a 'category' model as well, that we then associate with our 'products' model? (Products "must belong to at least one category"?)

**Comment by Lgerald** [comment]
YOOO we're also gonna need an isAdmin category for users! (it should be a boolean type, and default: false)

**Comment by ooong** [comment]
@Asterids 'categories' is listed as a column on the Product model, I think that should work right? It won't be an association, but we should still be able to filter products by their 'categories' field.

**Comment by ooong** [comment]
Thanks @Lgerald, edited the issue to reflect that!
