### ISSUE TITLE
Product routes (Unauthenticated Visitor)

### ISSUE THREAD

**Issue by Lgerald** [LERN-grace-shopper/grace-shopper#4]
As an unauthenticated visitor, I want to...
...view the full list of products (the product catalog), so that I can see everything that's available
...refine product listings by category, so that I can narrow down my choices to see only the types of items I'm interested in
...search product listings, so that I can find specific products I want by name
...view the details for an individual product (including product descriptions, photos and reviews), so that I can determine whether that particular item fits my needs

implementation:
-GET/all products route
--query all products route (GET/category listing)**
--search product route**
-GET/individual product id route

**Comment by ooong** [comment]
- [ x ] GET all products
   ** if we have time, could implement a function that checks to see if the inventory is less than a certain number (low inventory) and if so, res.json all the product information. if inventory is above a certain number (high inventory), return all the product information except for the inventory property
- [ x ] GET all products by category
- [ x ] GET product by id

  Will need to address search in the frontend
